version: 1.0.{build}

install:
- ps: |
      [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls
- cmd: >-
    gem install nokogiri -v 1.6.8.1

    generate.bat
build_script:
- cmd: build.bat

test_script:
- cmd: >-
    unit_test.bat

    appveyor_test.bat
