version: 1.0.{build}

image:
- Visual Studio 2022

install:
- dir C:\
- set PATH=C:\Ruby26-x64\bin;%PATH%
- ruby -v
- ps: |
    .\scripts\Generate-Message-Sources.ps1

before_test:
- ruby -v

build_script:
- ps: dotnet build -c Release --framework net6.0

test_script:
- ps: |
    dotnet test -c Release --no-build --no-restore UnitTests -l trx
    .\scripts\AcceptanceTest.ps1
