version: 1.0.{build}

install:
- cmd: >-
    set PATH=C:\Ruby22\bin;%PATH%

    gem install nokogiri

    gem install mustache

    generate.bat

build_script:
- cmd: build.bat

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
- cmd: >-
    unit_test.bat

    appveyor_test.bat
